### ISSUE TITLE
How to mock unit tests when using djangorestframework-api-key

### ISSUE THREAD

**Issue by platico** [florimondmanca/djangorestframework-api-key#103]
Hello there,

I am using `djangorestframework-api-key` and unfortunately since I implemented the custom permissions for the API key my unit tests started failing. Until now I was using `.force_authenticate` to mock the authentication but it doesnt seem to be enough after the API key implementation.

Can you let me know whats the best way to mock the tests?

**Comment by platico** [comment]
## Solution

I solved it with the way:

```python
        key = APIKey.objects.create_key(name="my-test-key")
       header = {'HTTP_X_API_KEY': key[1]}
       client = APIClient()
       data = client.get(self.url, data={'format': 'json'}, **self.header)
```

**Comment by florimondmanca** [comment]
Yes, creating a key programmatically and passing it in the headers (i.e. _not mocking_) is definitely the way to go. :)

Closing as this seems resolved now!

**Comment by mikebridge** [comment]
I had the same question as the OP and found that it's also possible to set up the APIClient with [`.credentials`](https://www.django-rest-framework.org/api-guide/testing/#credentialskwargs):

```python
client = APIClient()
client.credentials(HTTP_AUTHORIZATION=f"Api-Key {self.api_key[1]}")
response = client.get(...)
self.assertEqual(response.status_code, status.HTTP_200_OK)
```
