### ISSUE TITLE
Framework returns 'Authentication credentials were not provided', regardless of whether or not the header is provided.

### ISSUE THREAD

**Issue by alex-yobota** [florimondmanca/djangorestframework-api-key#111]
I'm not sure if this is a bug, or user error, but I'm having an issue in which all requests (no auth header, correctly formatted auth header, incorrectly formatted auth header), all return a 403 error with:
```
{
    "detail": "Authentication credentials were not provided."
}
```
Troubleshooting efforts:
- Tried cURL instead of Postman
- Written some dummy middleware to print the request - it definitely has a correctly formatted Authorization header.

My rest framework settings are as follows:
```
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework_api_key.permissions.HasAPIKey",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
}
```
I have read that this can be caused by not specifying a value for `DEFAULT_AUTHENTICATION_CLASSES`, but this is not mentioned in the djangorestframework-api-key docs. I tried specifying this as `[]`, which caused all responses (with or without an Authorization header) to return a 403 error with:
```
{
    "detail": "You do not have permission to perform this action."
}
```

Am I doing something wrong?

**Comment by florimondmanca** [comment]
Hi @alex-yobota!

Hmm, haven't seen this before. Can you share your Python, Django, DRF, and DRF API Key versions?

**Comment by alex-yobota** [comment]
Hi @florimondmanca, thanks for getting back to me!
```
Django==2.2.10
django-configurations==2.2
djangorestframework==3.11.0
djangorestframework-api-key==1.4.1
```

**Comment by florimondmanca** [comment]
> Written some dummy middleware to print the request - it definitely has a correctly formatted Authorization header.

How did you verify the `Authorization` header was present? We're doing `request.META.get("HTTP_AUTHORIZATION")`, I'm wondering if `Authorization` might be provided in a different way in your setup.

**Comment by alex-yobota** [comment]
I'm printing `request.headers.get("Authorization")`. Yes, it's correctly formatted, and matches the output of `request.META.get("HTTP_AUTHORIZATION")`

**Comment by florimondmanca** [comment]
Okay. At this point I have very little clue about what's going on…

What might help is to find the _minimal_ setup that triggers this issue. Perhaps start a blank DRF project, then add your settings one by one until you get the error…

**Comment by alex-yobota** [comment]
It doesn't have anything to do with this running locally over HTTP, does it?

**Comment by alex-yobota** [comment]
Ok, this is embarrassing. I've re-generated the API key, and it works now. Sorry!
As a minor point, though, perhaps an incorrect API Key (in a correctly formatted header) should generate a different error message to a missing Authorization header?

**Comment by florimondmanca** [comment]
Ah! 🤣 

> As a minor point, though, perhaps an incorrect API Key (in a correctly formatted header) should generate a different error message to a missing Authorization header?

Absolutely! Seems like this is possible via the [`message` permission class attribute](https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions). Would you like to give this a shot? :-)

**Comment by alex-yobota** [comment]
Sure!
Thank you for your help :)
