### ISSUE TITLE
Verify api key from view section

### ISSUE THREAD

**Issue by MexsonFernandes** [florimondmanca/djangorestframework-api-key#112]
I need to verify the API key from the view section, where client can add the key in POST data.

I checked the code and get_from_key() function is not available in 1.14.1. Need support for this.

**Comment by MexsonFernandes** [comment]
#102  this pull request can help

**Comment by florimondmanca** [comment]
Hi @MexsonFernandes :-)

If #102 would solve your use case then I am going to close this as a duplicate of #98.

(#102 seems stalled right now, if you'd like to contribute feel free to file a new PR based on that one. :-))

Thanks!

**Comment by MexsonFernandes** [comment]
api_key = APIKey.get_from_key(key) this is not available. How should I achieve it?

**Comment by MexsonFernandes** [comment]
api_key = APIKey.get_from_key(key) this is not available. How should I achieve it?

**Comment by florimondmanca** [comment]
Unfortunately I still have to cut a release for `.get_from_key()` and other items (refs #100). It's been a while to I'll try to get this done this weekend. :-)

**Comment by MexsonFernandes** [comment]
sure thanks.
