### ISSUE TITLE
Can the copyright years be replaced from "present" to "2020"?

### ISSUE THREAD

**Issue by utkarsh2102** [florimondmanca/djangorestframework-api-key#133]
Hi @florimondmanca,

Thanks for your work on this so far!
However, whilst maintaining this in Debian, I hit this bug: https://bugs.debian.org/956920

This maps to the following line:
https://github.com/florimondmanca/djangorestframework-api-key/blob/2f6c80c094a9ea6986d6efdfdea11a45b6686462/mkdocs.yml#L3
which says `2018-present`. Can this perhaps be replaced by the year, that is, `2018-2020`?

TIA :)

**Comment by florimondmanca** [comment]
Hey!

Oh... Sure okay, sounds legit :) I’ll take a look soon.

**Comment by utkarsh2102** [comment]
> Oh... Sure okay, sounds legit :) I’ll take a look soon.

Perfect, thanks :taco:
