### ISSUE TITLE
permission_classes for all views

### ISSUE THREAD

**Issue by ManPython** [florimondmanca/djangorestframework-api-key#136]
How to easy implement `permission_classes = [HasAPIKey | IsAuthenticated]` in whole views of APIs?
In urls?

**Comment by florimondmanca** [comment]
Heya,

I think this is a DRF usage question, but IIRC you can declare your custom combined permission class somewhere, and then point your DEFAULT_PERMISSION_CLASS (not sure about the name there?) in settings.py:

```python
# project/permissions.py
MyPermission = HasApiKey | IsAuthenticated

# settings.py
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASS": "project.permissions.MyPermission",
}
```

**Comment by ManPython** [comment]
Look like good idea but have error:
```
Python36\lib\site-packages\django\conf\__init__.py", line 176, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```
Of course I have SECRET_KEY

**Comment by bill-pairaktaridis** [comment]
No clue why this was closed. Did you figure it out, @ManPython ?
