### ISSUE TITLE
Abstract models keys?

### ISSUE THREAD

**Issue by ManPython** [florimondmanca/djangorestframework-api-key#137]
I need add more fields for `apikeys` eg. relations with pk.custom_user as relation key for user, and other atributes.
Should I manipulate with `rest_framework_api_key_apikey` or model - in case of future perspective of this framework?

**Comment by florimondmanca** [comment]
Hi,

Sure, I think it’s safe enough to use this table name. Anything documented should be considered public API, so this table name that comes from the package name and model name is indeed public API (and will be handled carefully should we decide to change names there, although very unlikely).

By the way quick questions like these feel free to drop by https://gitter.im/florimondmanca-oss/community.

**Comment by ManPython** [comment]
Did you get some reflection near about `admin/authtoken/token/`?
Eg. in this model as `Auth Token` with `Token` can be `Api keys` as now `API Key Permissions` with `Api keys`. I want sugest changes and made some sheme for this type modifications in future with new cols - maybe need some help to reach some standards in fork.

PS. Chat is ok, but the code, searching in git is good solution.
