### ISSUE TITLE
Test Authorization Api-Key by clients - problems

### ISSUE THREAD

**Issue by ManPython** [florimondmanca/djangorestframework-api-key#138]
I meet strange issues around test Authorization Api-Key by clients.
Eg. working in Firefox RESTer, and not working RESTclient.

Similar in many cases not working python.

```
import requests

response = requests.get(
    url="http://127.0.0.1:8000/api/?format=json",
    headers={
        'Content-Type':'application/json',
        'Authorization':'',
        'Api-Key':'JPzs45ac.qwerty......',
    },
)
print(response)
print(response.json())
```
```
<Response [401]>
{'detail': 'Authentication credentials were not provided.'}
Unauthorized
```
I'm using
```
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
```
If coment `#'rest_framework_jwt.authentication.JSONWebTokenAuthentication',` then http 403.
Need some more configs here?

**Comment by florimondmanca** [comment]
Hey,

I’d appreciate if you could be more mindful that opening issues for Django/DRF usage questions like these does not feel great on the receiver side. This is not what a project’s issue tracker is for.

Please be aware that by opening issues like these here you are asking me to dedicate some of my free time to these questions (if only to go ahead and close them off after writing friendly messages such as this one). But I have no obligation to, and likewise you shouldn’t feel entitled to anything from the community.

Having said this, I hope you’ll understand why I’m going to close this and won’t follow up on the other two issues. I’m sure you’ll be able to figure things out eventually through a bit of googling, or asking on help forums like StackOverflow.

Thanks.

**Comment by ManPython** [comment]
I understand the open source community. We together working for future of bether solutions as colective community. If I reported problem then other users can meet this same and safe time. This is the role of OS community and not other. You should not close issue, maybe wait for more colaboration team to suppor this part of framework. Here how we working around github often. Some one testing while implementing, after feedback and sugestion we made improvments to grow and solve problems.
