### ISSUE TITLE
Work with Django Rest Auth

### ISSUE THREAD

**Issue by elkarouani** [florimondmanca/djangorestframework-api-key#139]
Hi, thank you for your valuable package, i will use it in my project, so far i put authentication feature on my project by implementing Django Rest Auth, after checking all the endpoints related to the authentication feature, i installed this package and i did what is written on the documentation :
- Adding "rest_framework_api_key" in the INSTALLED_APPS list
- Migrating using the command : python manage.py migrate
- Set Permissions globally HasApiKey in settings.py
And when i test, for example, the Sign In endpoint without the header option on the request, i sign in successfully, and when i add the header option on the request like what it said on the documentation, i get the response "CSRF Failed: CSRF token missing or incorrect." with the status 403.

I generated the key from the admin interface. Did i miss something here ?

**Comment by florimondmanca** [comment]
Hi,

I’m not sure I understood what the problem is exactly (ie what you expected to happen), but...

I’m not familiar with Django Rest Auth, not with its setup, but I’d expect the addition of the permission class to somehow mess up DRA’s endpoints because your app would now be expecting an API key.

So you might want to be more subtle and enable the permissions only on views that require it, instead of globally.

Hope this helps. Going to close since for now so I don’t see a problem with this package, but feel free to continue discussion.

**Comment by elkarouani** [comment]
With Django Rest Auth, i use some endpoints built in that last like login, logout, register ...etc. There is no views for these endpoints in my project so i can set the permission there, when i test an endpoint of login, when i don't pass any header in that request, the response i get is the token, the expected response should be a permission denied for not passing an Authorization key, and when i pass the header on the request i get the response "CSRF Failed: CSRF token missing or incorrect." with the status 403.

For the login there is no token related to the DRA to pass it with the request
I hope you understand this situation, other than that you can suggest a guide on how we can work with this package and the Django Rest Auth.

Waiting for your reply, and thank you again for your attention.

**Comment by florimondmanca** [comment]
> you can suggest a guide on how we can work with this package and the Django Rest Auth.

Sorry, like I said I’m not failing with Django Rest Auth, and respectfully I don’t _have_ to take on my free time to dig into this for you.

I think the next step forward for you might be to dig into the Django Rest Auth source code to better understand what it does in general and in terms of permissions. Eg I’m not sure where the CSRF error comes from, given that this is generally related to HTML pages but Django Rest Auth should be operating JSON endpoints...

If you end up finding a problem in this package or something that would make it easier to integrate with Django Rest Auth then I’d be happy to discuss further!

Thanks.
