### ISSUE TITLE
[question] Where to find the API Key details?

### ISSUE THREAD

**Issue by neowenshun** [florimondmanca/djangorestframework-api-key#140]
Sorry if im asking a dumb question , i have been trying to use this to authenticate requests between 2 projects, A and B. A is the project that is generating the Key , while B is the one making the requests to A's endpoint. I have installed this package to project A , and have generated a Api key via the django-admin interface. However , it is only showing the prefix. If this is a expected behaviour , how then would i go about getting the entire API key over to project 'B' so that it may be used as the auth headers? ?

**Comment by florimondmanca** [comment]
Hi,

Full API keys are not accessible in the admin list view. They’re only visible at creation.

When you create an API key in the admin of project A, there’s a one-time banner that shows up at the top in the with the full API key. You can copy that and paste it somewhere in project B.

Hope this helps.
