### ISSUE TITLE
Cant create API Key - Error: "Unknown column 'prefix' in 'field list'"

### ISSUE THREAD

**Issue by DmitryOnishchuk** [florimondmanca/djangorestframework-api-key#147]
**Describe the bug**
After install Django REST Framework API Key and make "python3 manage.py migrate" i have an error with create API Key in admin panel, error message: Unknown column 'prefix' in 'field list'. Please check it.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Version: 2.0
 - Python Version: 3.8.2
 - Django Version: 2.2.12
 - DRF Version: 3.11.1

**Screenshots**
![error](https://user-images.githubusercontent.com/71881712/94263319-88b6f100-ff3d-11ea-834a-035e156fba87.png)

**Comment by florimondmanca** [comment]
Hello!

> Please check it.

Not sure how you meant this to come across, but please be aware that as a volunteer-based open source nobody here is in a position to require anyone's time. :)

That being said, from your screenshots there are a few questions I'd have to move this forward:

- You wrote this happens in the admin. What exact series of steps could somebody use to reproduce this error? For example, "1/ Opn admin site, 2/ Go to API Keys, 3/ Click new API key, 4/ Submit form, error occurs".
- I've been moderately engaged with this project recently, so could we verify that `prefix` is indeed a known model field?
- Are you doing any kind of customization that could lead the prefix field to not be defined in your custom model?
- Etc...

**Comment by florimondmanca** [comment]
Going to close assuming this got solved eventually, thanks.
