### ISSUE TITLE
Support mongoengine 'Document' in place of Django 'models.Model'

### ISSUE THREAD

**Issue by dblado** [florimondmanca/djangorestframework-api-key#153]
**Is your feature request related to a problem? Please describe.**
I use mongoengine for my Dango app. Mongoengine is supported in DRF by a 3rd party library @ http://umutbozkurt.github.io/django-rest-framework-mongoengine/index.html

**Describe the solution you'd like**
I think creating an AbstractAPIKey that inherits from mongoengine.Document would probably satisfy the requirements. Perhaps use a setting like API_KEY_MONGOENGINE to determine if APIKey is a Django model or mongoengine Document would be easy to implement.

**Comment by florimondmanca** [comment]
Hi @dblado 

Given the maintenance constraints on this package, I have doubts this would make it into core for now should you find something that works for your use case.

If this is still something you're interested in, I'd suggest rolling with a fork, a local custom solution, or something in that vein.

Thanks!
