### ISSUE TITLE
error in HasApiKey permission

### ISSUE THREAD

**Issue by souheyltoumi** [florimondmanca/djangorestframework-api-key#154]
**Describe the bug**
error in HasApiKey permission when trying to call the api i get  invalid credentials error i think the problem is in the crypto.py file

**Comment by florimondmanca** [comment]
@souheyltoumi Hi. Could you follow the `Bug Report` issue template, providing necessary details as listed there? Right now this issue is not actionable. Thanks!

**Comment by souheyltoumi** [comment]
@florimondmanca 
Describe the bug
request always return unvalid credentials when adding HasAPIkey to permissions_classes
To Reproduce
Steps to reproduce the behavior:

create a simple class
from rest_framework_api_key.permissions import HasAPIKey
class ProjectListView(APIView):

permission_classes = (HasAPIKey,)

def get(self, request):
    """Retrieve a project based on the request API key."""
    return HttpResponse("SUCCESS")
Configure urls
3.generate apikey
4.at postman configure the header as its stated in the user guide
5.when accessing that Url we get unvalid credentials
Expected behavior
expect to get the result success
Screenshots
![image](https://user-images.githubusercontent.com/56138763/101212354-ddcb5d80-3678-11eb-8131-23600ead6d4c.png)

If applicable, add screenshots to help explain your problem.
image

Desktop (please complete the following information):

OS: Windows
Version: [e.g. 0.2.2]
Python Version: [e.g. 3.7]
Django Version: [e.g. 2.1]
DRF Version: [e.g. 3.8.2]
Additional context
Add any other context about the problem here.

**Comment by richardARPANET** [comment]
Also experiencing this issue

```
djangorestframework==3.12.2
djangorestframework-api-key==2.0.0
```

Despite following all the instructions, when a request is sent to the server including a valid 'Authorization' header. The server responds with:

```
403

{
    "detail": "Authentication credentials were not provided."
}
```

**Comment by richardARPANET** [comment]
@souheyltoumi found the issue. It's that the documentation is wrong. It suggests supplying just the api key PREFIX with requests. When you actually must pass the full api key in the header.

e,g,

```
VALID
e1A90iCP.qg7Hn5JOKsSzZYG8NoneihxXVO24QhOi.

NOT VALID
e1A90iCP
```

**Comment by florimondmanca** [comment]
> you actually must pass the full api key in the header.

Yup, that's correct. I see now in @souheyltoumi's screenshot that they seem to have passed the prefix only, but the full API key is required.

>  It's that the documentation is wrong. It suggests supplying just the api key PREFIX with requests.

This doesn't seem to be what the docs here point at…? https://florimondmanca.github.io/djangorestframework-api-key/guide/#authorization-header Or is "the generated API key" ambiguous, i.e. it could be understood by "the visible part of the API key that's shown to you in the admin"?

**Comment by richardARPANET** [comment]
Nobody reads docs word by word, readers skim over things and just read code blocks usually.
This part is what's misleading:

```
then clients must make authorized requests using:

X-Api-Key: ********
```

it should be more like:

```
then clients must make authorized requests using:

X-Api-Key: ********************************
```

**Comment by souheyltoumi** [comment]
thank you @richardARPANET and @florimondmanca

**Comment by florimondmanca** [comment]
> `********************************`

Yup, agreed. :-) I'll log a ticket about this so we properl track it.

Thanks all.

**Comment by souheyltoumi** [comment]
hey @richardARPANET  how do i get the full Api key

**Comment by richardARPANET** [comment]
@souheyltoumi When you create it in the Django admin panel it shows on UI at that moment (and never again).

**Comment by ArnaudNorel95** [comment]
Sorry but I've got the same error with entire API-Key,

I tried absolutely everything :
First I tried in Authorization as mentionned in the doc
so with Api-Key then with X-Api-Key as you mentionned @richardARPANET 
![image](https://user-images.githubusercontent.com/46846856/124231463-96268a80-db10-11eb-916e-4d8467529796.png)
![image](https://user-images.githubusercontent.com/46846856/124231503-a474a680-db10-11eb-904f-7439a8e035cc.png)

It didn't work so I follow the method of @souheyltoumi  and put Api-Key in my params as following : 

 Authorization=X-Api-Key: juWYFxem.i512sP5Uo70kho4ni5RaF6z2ZT1kLgDw
 Authorization=Api-Key: juWYFxem.i512sP5Uo70kho4ni5RaF6z2ZT1kLgDw

I tried with uppercase , lowercase ... This problem makes me mad !
The doc says : 
Authorization: Api-Key <API_KEY> 
What am I doing wrong?

Of course I added in my views.py:
`permission_classes = [HasAPIKey]`

and in my  settings.py : 
```
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework_api_key.permissions.HasAPIKey",
    ]
}
```
