### ISSUE TITLE
Redacted API key hints in docs should more clearly indicate to use the full API key

### ISSUE THREAD

**Issue by florimondmanca** [florimondmanca/djangorestframework-api-key#157]
Prompted by https://github.com/florimondmanca/djangorestframework-api-key/issues/154#issuecomment-745314245

Right now, if we skim our [docs](https://florimondmanca.github.io/djangorestframework-api-key/guide/) we see usage hints like these:

```
then clients must make authorized requests using:

X-Api-Key: ********
```

But this may be misleading readers to conclude that the `*******` should be replaced with the API key prefix (since it "fits" in length much better than the full API key).

Instead, those parts of the docs should look like this:

```
then clients must make authorized requests using:

X-Api-Key: ********************************
```

So that it's clearer that the full API key should go in there.

Happy to review any pull requests for clarifying this!

**Comment by souheyltoumi** [comment]
hey @florimondmanca  how do i get the full API Key its not included
