### ISSUE TITLE
Authentication with DRF_API_KEY_SECRET_KEY_HEADER only

### ISSUE THREAD

**Issue by ssrebelious** [florimondmanca/djangorestframework-api-key#16]
**Is your feature request related to a problem? Please describe.**
It would be handy to allow client to use only a secret key value `DRF_API_KEY_SECRET_KEY_HEADER` to access endpoints.

**Describe the solution you'd like**
Client software provides only `DRF_API_KEY_SECRET_KEY_HEADER` and has its access to the endpoints and it is clear on the Django side to which client this key belongs to.

**Describe alternatives you've considered**
Adopt [DRF token authentication](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) for non-human clients.

**Comment by ssrebelious** [comment]
Glad to hear that you are worried about security issues (so am I). I'm not a hacker of any sort, just having a couple of Django apps that I need to create infrastructure to be able to communicate with them by third party applications that should not have any login/pass to be able to access to the certain endpoints.

There are many online projects that allow to interact with them using only an API key: gmail, git-lab, git-hub, etc. There are plenty of read-only APIs (by well-established companies) that requires you to only provide `?api_key=some_api_key` in get request to access data. I guess the whole point of using api-keys is to have only the key to access resources without need of any additional information. I'm not an expert in API-keys infrustracture and not aware of the practices used on backends, but having a lot of experience of interacting with APIs that requires just a key to access them I wonder how could I provide my users with similar experience.

**Comment by ssrebelious** [comment]
Yes permanent (or with manageable lifetime) server-to-server application tokens seems to be what I'm looking for. 

Let me describe a particular use-case I'm working on. The resource-application has _users_ (humans) - basically admins and _clients_ - other applications that use its resources. Administrator creates a client record and gets a permanent api-key/token for the given third party application. This key is delivered to the administrator of the client application and he stores it on the server side of the client application. Backend of the client application is able to use endpoints of the  resource application using only API-key/token. Users of the client-applications don't even know about existence of such key /token or even about resource-application itself.

**Comment by florimondmanca** [comment]
Yes, that makes sense and this is exactly the kind of use case this package is meant for. :)

So, just to be certain — you are in the position of an API provider (similar to GitHub or another data provider such as OpenWeather API), and you would like your users to be able to generate a single-item API key, store it on the server side and use it to perform read-only operations on the API, correct?

I suppose then, that the issue of having 2 separate credentials is only that of UX from your users perspective?

Just to clarify — single-item API key is not the only scheme out there. One important example is AWS whose IAM service relies on granting *access keys* which are in two parts as well (*access key ID* and *secret access key*). Maybe it is fine to explain your users that your particular API requires them to provide both items.

**Comment by ssrebelious** [comment]
> I suppose then, that the issue of having 2 separate credentials is only that of UX from your users perspective?

Yes, UX is better with a single key only without any additional ID's. I do integrate your library and will have to use both ID and the key (as there are no other options at the moment), though I would like to implement desired behaviour in feture if this package will provide needed functionality.

I want access to my API to be as simple as this example from `geocoder`:
```python
>>> import geocoder # pip install geocoder
>>> g = geocoder.bing('Mountain View, CA', key='<API KEY>')   # notice that only API-key is required
>>> g.json
...
```

**Comment by florimondmanca** [comment]
Okay, so here's the plan:

We're going to change how API keys are currently implemented to a single-header scheme.

Here's the lifecycle of the new API key:

1. Admin user generates an API key in the Django admin site. The API key is shown on screen but only a hash is stored in the database.
2. Admin user sends API key to client user.
3. Client user can authenticate using the `Authorization` header, e.g. `Authorization: Api-Key abc123`.
4. Verification is performed by comparing hashes of the API key sent by the client and the hash stored in database.

The current scheme could be re-implemented later and branded as "access keys", if needed.

Would this be satisfying @ssrebelious? 😄

**Comment by ssrebelious** [comment]
`some-backend-service:abcd1234` looks like `user:pass` in basic authentication scheme. The user part is redundant in this case, so `Authorization: Api-Key abcd1234` should be sufficient to my mind.

**Comment by florimondmanca** [comment]
That’s because it mostly is what it is. The name part is used to find the API key, and the secret key is used to check whether the keys match. Since API keys are not stored in plain text in the database (but encrypted just like passwords), we can’t just have the user pass the secret key because we wouldn’t know against which API key to compare it to. :-)

So the name:key format is used to extract the name easily. If name and secret key are concatenated then we can’t extract the identifying name.

Does that make sense?

**Comment by ssrebelious** [comment]
With such approach this will be the same functionality as before but implemented in slightly different way. The feature I asked for is the ability to use **api key only** to identify user. I think that API key have to be auto-generated and unique. If stored as a hash, a hash has to be unique. So when the key is provided, having its hash is enough to identify the user because hash is unique across all users and bounded to one and only one user.

**Comment by florimondmanca** [comment]
Yes, I see. I thought it would be more secure to implement a key pair pattern but in the end your users will end up passing the api key as a single string; they won’t need to know that there is a name and a secret key. They’ll treat the whole thing as a secret so it’s esuivalent to having just a secret key. Plus as you said if we make sure the hash is unique then we’re good for the validation step, and becaus it is hashed and the key is never stored in clear on the server there are no confidentiality issue.

I’ll open a PR for this implementation instead. :-)

**Comment by florimondmanca** [comment]
Okay, I updated #19. Here's the updated scheme:

1. Admin user generates a named API key in the Django admin site. The secret key is shown on screen.
2. Admin user sends secret key to client user.
3. Client user authorizes using the `Authorization` header, e.g. `Authorization: Api-Key abcd1234`.
4. Verification is performed by comparing hashes of the secret key sent by the client to the hashes of the unrevoked API keys present in the database.

Does that sound right to you now in terms of workflow @ssrebelious?

**Comment by ssrebelious** [comment]
Yes, that sounds legit. In actual workflow of mine users obtains keys by registering themselves via dedicated endpoint not by administrator. 

I think that field with hashes should be indexed by default.

**Comment by florimondmanca** [comment]
Cool!

> I think that field with hashes should be indexed by default.

Hmm, why should it be? We're not filtering the queryset nor doing any grouping/ordering while checking for permissions. In fact we need to pull out the `encoded` key of each API key and perform a hash check against each of them until we find one that matches. This is because I don't think there's a way to identify which API key could should be checked solely based on the plain text key (since we store hashes in the DB). Am I missing something?

**Comment by ssrebelious** [comment]
I am worried about scalability. For example the case when we have over 1 000 000 users. I think it is worth to test the performance... On the second thought the `unique` index will be created in PostgreSQL for the field with hashes, it should be used by DBMS for exact match queries... Guess other DBMSs creates unique index as well... So there is not point for extra index indeed.

**Comment by florimondmanca** [comment]
I agree with you that performance *is* a concern.

Besides being O(N), the current implementation requires O(N) cryptographic computations which can be especially expensive.

However, even if there was an index on the `encoded` key field (either set by us or the DMBS using the unique constraint), we wouldn't be able to use it.

This is because Django's hashing utilities use salting to be cryptographically strong. This implies that hashing is non-deterministic; the following code would use the index, but it wouldn't work in practice:

```python
key = get_key_from_header(request)
encoded = encode(key)
granted = APIKey.objects.filter(encoded=encoded, revoked=False).exists()
```

because `encoded` will not be the same as the `encoded` string stored in the database even if the `key` is correct (since `encode()` would use a different salt than the one used initially).

(FYI, I am basing this reasoning on the [Django password management guide](https://docs.djangoproject.com/en/2.1/topics/auth/passwords/).)

So this means tat, unless we have a means to identify the key, we need to perform a cryptographic check against *all* API keys, which is the current implementation in #19.

The purpose of the `name` was to be able to retrieve a single API key (using the index) and perform a cryptographic check *only* on that one, which would be much more scalable. If that makes sense and if you don't care having the `name:secret_key` format (which clients can still treat as a single API key), we can revert to this implementation which, unless I'm mistaken, satisfies the use case of having a single header.

**Comment by ssrebelious** [comment]
Googled a bit on practices of implementing API keys. And there are two approaches that can be used in order to achieve an **api key only** access and have decent performance.

1. Using prefix in the api key. This is similar to the approach that you already implemented. The key is represented as `{unique_prefix.secret_key}`. [Here is the link](https://medium.freecodecamp.org/best-practices-for-building-api-keys-97c26eabfea9). Prefix here is used to locate hash stored in the database and secret key - to obtain hash for comparison. Prefix is not user name per se, but a unique value associated with the user. User have no clue that the key consists of two parts in the first place. I think prefix must be unique per key, so the user would get completely new prefix for each new key and wouldn't be able to conclude for sure that this prefix is his latent id.
2. Storing plain text tokens in the database. [The idea of the approach is described here](https://stackoverflow.com/a/37953361/2648947). Here we have only one secret key for every api-key and we can use Django's secret key for this. API key is the result of the function `generate_api_key(USER_TOKEN, DJANGO_SECRET_KEY)`. Token can be just a UUID that is stored in the database in plain. We need another function `retrieve_token(API_KEY, DJANGO_SECRET_KEY)` to get token from API key and find the user it belongs to as exact match against a DB record. This approach is vulnerable to unrecoverable loss of secret key (due to hardware mailfunction for example) - there would be no way to  extract tokens from existing keys. Also stuff with access to secret key will be able to obtain keys for every user.

**Comment by ssrebelious** [comment]
By the way. What about adding multiple keys per user?

**Comment by florimondmanca** [comment]
Okay, thanks a lot for the link to the Medium article, that's definitely very helpful.

As you noted I think the second approach induces more confidentiality risks (admins could read API keys provided they know how the signing system works). So I'm more inclined towards the first option, which indeed looks like the scheme I was trying to implement initially. Now I realise that the "prefix" needs to be a unique random generated string too, whereas before it was an easily identifiable piece of information (free-form text).

I'll follow the article to implement this new scheme, including displaying the prefix in the admin to easily identify keys.

Do we agree that being able to add a free-form `name` to an API key is useful, although not used in the actual authorization mechanism? This way we can know that API key xyz relates to, say, the "News streaming service".

> By the way. What about adding multiple keys per user?

As in, can it be done at the moment and how? I think it can. API keys are not related to users, they're standalone so in theory you can just create multiple keys for the same client. Are you thinking of something else?

**Comment by ssrebelious** [comment]
> Do we agree that being able to add a free-form name to an API key is useful, although not used in the actual authorization mechanism? This way we can know that API key xyz relates to, say, the "News streaming service".

Yes.

> API keys are not related to users, they're standalone so in theory you can just create multiple keys for the same client.  Are you thinking of something else?

I'm thinking about multiple keys for one client, managing expiration dates, etc. I think this should be discussed in separate feature request when this one will be closed.

**Comment by florimondmanca** [comment]
> I'm thinking about multiple keys for one client, managing expiration dates, etc. I think this should be discussed in separate feature request when this one will be closed.

Yes, we can build upon this in the future to add things like expiration dates, client IDs, API key scopes (i.e. permissions), etc. :-)

**Comment by florimondmanca** [comment]
Okay so, an update on this: @orlax raised the concern in #24 that if we use the `Authorization` header for API keys, then we're not able to use any other authentication mechanism built into the DRF, such as basic auth or token auth.

I still believe using `Authorization` is a good default regarding the HTTP spec, so we should make it possible to use a custom header. So a `API_KEY_CUSTOM_HEADER` setting defaulting to `None` (i.e. use `Authorization`).

**Comment by ssrebelious** [comment]
That is nice solution. Are there chances that version 1.0 will be released  this week? It would be great  if I'll be able to start refactoring of my application next week.

**Comment by florimondmanca** [comment]
Yep, I think that’s doable @ssrebelious! 👍

**Comment by florimondmanca** [comment]
I’m closing this now since all changes were merged into dev/1.0.

**Comment by florimondmanca** [comment]
@ssrebelious 1.0 is out 👍

**Comment by ssrebelious** [comment]
Great job! :clap:
