### ISSUE TITLE
MIgration from  0.4.0 to 1.x.x failed

### ISSUE THREAD

**Issue by drrr-deudeu** [florimondmanca/djangorestframework-api-key#161]
**Describe the bug**
Old data model isn't recognized. 
In other hand migration files aren't produced

**To Reproduce**
1. Edit your app/requirements.txt of your django 1.11 application
2. clear all versioning of your packages except change Django==1.11 to Django==3.1
3. fix or not a specific version of django-restframework-api-key (any version > 0.4.0)
4. rebuild and start your app
5. start  log show that the model isn't anymore recognized.
6. start pyton manage.py makemigrations : any migration build
7. python manage.py migrate : "nothing to do" message

**Workaround**
keep a fix version 0.4.0
It works (no error generated by django) but... the api keys need to be re-generated

**Expected behavior**
Transparent migration (except run python manage.py migrate...) and keep the keys valid
For sure a better workaround than mine is also welcome! (drop api-keys tables and install last version?... but my keys... :( )

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [debian jessie]
 - Version: []
 - Python Version: [3.6.8]
 - Django Version: [1.11 --> 3.1]
 - DRF Version: [3.6.4 --> 3.12.2]

**Additional context**
The issue could be a big issue in case of app with many keys

**Comment by florimondmanca** [comment]
Hi!

Some ideas...

- Have you tried bumping to Django 2 as an intermediate step between 1.11 and 3.0? The migration guide was written before 3.0 was out, I believe.
- Ideally there should be a way to migrate your data manually, but I haven't worked with Django's ORM extensively enough for a while to be sure about how to proceed. I would mean: export your table to SQL (a table dump), migrate forcibly (perhaps needs dropping table contents beforehand), then perform the import manually after having manually done the migration operations separately on the SQL data (could be a Python script using psycopg2 or any appropriate database client).

**Comment by drrr-deudeu** [comment]
I'm just trying first idea:
- migrate to django2 (app/requirements without freeze versions except Django==2)
- And:
root@cb899397870a:/srv/app# python manage.py makemigrations
No changes detected
root@cb899397870a:/srv/app# python manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, ircamauth, oauth2_provider, rest_framework_api_key, sessions, sites, socialaccount, thumbnail
Running migrations:
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying rest_framework_api_key.0002_auto_20190529_2243... OK
  Applying rest_framework_api_key.0003_auto_20190623_1952... OK
  Applying rest_framework_api_key.0004_prefix_hashed_key...Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column rest_framework_api_key_apikey.name does not exist
LINE 1: ...."id", "rest_framework_api_key_apikey"."created", "rest_fram...
                                                             ^
Note also:
root@cb899397870a:/srv/app# pip list |grep api
djangorestframework-api-key 2.0.0

**Comment by drrr-deudeu** [comment]
After some investigations. trying the example_project from scratch, 
There is a model alteration of the API Key table between 0.4.0. and 1.0.0, but don't take in charge by the new version.
For example, in the is unique migration file, 0001_initial.py, there is any reference to the older field 'client_id' , seems rename to 'name'

**Comment by florimondmanca** [comment]
(Coming back to this repo after a while.)

@drrr-deudeu I did some digging. Right, you're correct, in 0.4.0 `initial_0001.py` was using `client_id`: https://github.com/florimondmanca/djangorestframework-api-key/blob/df24cece567f930d272d7c205e9bbed8a3635ffb/rest_framework_api_key/migrations/0001_initial.py#L27                 

There were breaking changes in 1.0.0 (design flaws got fixed) and this means the migration 0.4.0 -> 1.0.0 requires _resetting migrations_ (erasing existing keys), as per the guide here: https://florimondmanca.github.io/djangorestframework-api-key/upgrade/1.0/. First do a backup, then reset migrations as explained in the guide, then upgrade to 1.0.0 (or 2.2.0, which supports Django 3). You can then use your backup to restore previous API keys. Unfortunately this will have to be done on your end; I can't provide a general solution.

Closing for now, but if you have more questions feel free to reach back and we can convert this to a discussion.
