### ISSUE TITLE
401 not authorized if not api_key.is_valid(key):             raise self.model.DoesNotExist("Key is not valid.")

### ISSUE THREAD

**Issue by ulziiburend** [florimondmanca/djangorestframework-api-key#162]
Recently I've tried to use this library, unfortunately, I've got some difficulties. It gives me 401 error.

my views.py
```
class LemondRegister(APIView):
    permission_classes = [HasAPIKey,]
    parser_classes = (parsers.MultiPartParser,)
```
postman request

![Screen Shot 2021-03-17 at 10 29 13](https://user-images.githubusercontent.com/7325885/111405689-e4ec1800-870b-11eb-83c2-d93231f8de2f.png)

I've tried to debug it and got False return for this part of code
```
        if not api_key.is_valid(key):
            raise self.model.DoesNotExist("Key is not valid.")
```
Any help?

**Desktop**
 - OS:MacOS
 - Version:2.0
 - Python Version: 3.7
 - Django Version: 3.013
 - DRF Version: 3.12.2

**Comment by florimondmanca** [comment]
@ulziiburend Heya,

See also #157: you'd need to enter the entire API key which has the form `xxx.xxxxxxxx`, rather than only the `prefix` like you did here. The full API key is shown only once in the admin upon creation. :-)

Thanks
