### ISSUE TITLE
How to use this library, why i always get Authentication credentials were not provided.

### ISSUE THREAD

**Issue by jemmycalak** [florimondmanca/djangorestframework-api-key#17]
![untitled](https://user-images.githubusercontent.com/19152608/52061282-8e113c00-25a0-11e9-9112-5a2c3af691ab.png)

What i am missing ?

**Comment by florimondmanca** [comment]
Hi,

If I'm not mistaken, "Authentication credentials were not provided" is a message returned in case of a `401 Unauthorized` error, i.e. one that has to do with authentication and not with permissions.

Which makes me wonder:

- Have you included the JWT in your request?
- Is everything going well with your JWT authentication only?

**Comment by jemmycalak** [comment]
-yes, response status is 403
-i was try jwt, jwt use key Authorization, i think Api-Token key replace to Authorization, and then i dont know value of Api-Token is it
-no, the response like before with 403 error code

**Comment by florimondmanca** [comment]
- My last question was actually: is everything going well if you remove API key entirely, i.e. remove it from `DEFAULT_PERMISSION_CLASSES` and also from `permission_classes` from  the `Index` view?
- API key permissions still requires authentication checks to pass. In your case, I think this means that the JWT is required even if you pass an API key. From your answer, I'm not sure you passed the JWT, did you?

**Comment by jemmycalak** [comment]
i was remove JWT from DEFAULT_PERMISSION_CLASSES and get same error with 403 code error, 

what value of Api-Token key ?

**Comment by florimondmanca** [comment]
The value for `Api-Token` should be the one listed in the admin. :-)

**Comment by jemmycalak** [comment]
is my Api-Scret-key value is correct ? like i generate on admin web ?

**Comment by florimondmanca** [comment]
Yes, `Api-Secret-Key` is the one that you are given in the admin site when creating the key (just like you highlighted).

**Comment by jemmycalak** [comment]
hemm,, I was found another way for use API key : 
https://github.com/manosim/django-rest-framework-api-key

its working for me.

**Comment by florimondmanca** [comment]
Okay, if manosim’s package is working for you, then fine. :-)

I am closing this issue, but I ‘d like to investigate and see if your issue was reflecting an important problem with this package. Would you mind sharing your specs (Python version, OS, version of djangorestframework-api-key)?

Thanks!
