### ISSUE TITLE
RemovedInDjango41Warning due to default_app_config

### ISSUE THREAD

**Issue by danfoster** [florimondmanca/djangorestframework-api-key#170]
**Describe the bug**

When starting a django application using this application on django 3.2, it generates this warning:

```
../usr/local/lib/python3.9/site-packages/django/apps/registry.py:91
  /usr/local/lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'rest_framework_api_key' defines default_app_config = 'rest_framework_api_key.apps.RestFrameworkApiKeyConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 2.0.0
 - Python Version: 3.9.2
 - Django Version: 3.2
 - DRF Version: 3.12.4

**Additional context**

See this for how the django_extensions handled this: https://github.com/django-extensions/django-extensions/pull/1654/files

**Comment by syth0le** [comment]
is there any news?

**Comment by florimondmanca** [comment]
@syth0le Hi :) I'm happy to review any changes worth making to handle this…

Let's not remove any compatibility _yet_ (e.g. with Django >=3.0, <3.2), although we might want to consider that, perhaps based on Django's own compatibility schedule?
