### ISSUE TITLE
"Should I use API keys?" documentation link is broken 

### ISSUE THREAD

**Issue by Mukhametvaleev** [florimondmanca/djangorestframework-api-key#176]
**Describe the bug**
`Should I use API keys?` documentation link is broken (404 Site not found).

**To Reproduce**
Go to:
https://florimondmanca.github.io/djangorestframework-api-key/guide/#api-key-models
Click `Should I use API keys?` link.

**Screenshots**
<img width="857" alt="image" src="https://user-images.githubusercontent.com/8947056/132040687-c643c4e8-ced6-4b6e-9d3f-19a8222dfa1b.png">

**Comment by florimondmanca** [comment]
Thanks for flagging this. It looks like the `djangorestframework-api-key` prefix in the URL path is missing. Anyone up for looking into that is much welcome!

**Comment by brittandeyoung** [comment]
It is not allowing me to link the PR to this issue, but I just opened a PR that will resolve this issue. 

#177
