### ISSUE TITLE
Type Error on APIView permission classes

### ISSUE THREAD

**Issue by vince015** [florimondmanca/djangorestframework-api-key#186]
**Describe the bug**
I am getting the following error:

File "/****/profile.py", line 62, in ProfileDetail
    permission_classes = [HasAPIKey | IsAuthenticated]
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**To Reproduce**
1. Update permission class on a view
**settings.py**
```python
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework_api_key.permissions.HasAPIKey'
    ),
```
views
```python
class ProfileDetail(APIView):

    permission_classes = [HasAPIKey | IsAuthenticated]

```

2. run *python manage.py runserver*

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.7
 - Python Version: 3.7
 - Django Version: 2.0
 - DRF Version: 3.7.3

**Comment by florimondmanca** [comment]
Hi @vince015,

Seems like you'd need to upgrade your DRF version to use the `&` / `|` functionality, as it was introduced in DRF 3.9. See [DRF 3.9 announcement](https://www.django-rest-framework.org/community/3.9-announcement/#composable-permission-classes).

Closing this for now, but if upgrading does not fix it, feel free to reach back!

Thanks
