### ISSUE TITLE
How to list al available api keys from account.

### ISSUE THREAD

**Issue by MatthiasMuller** [florimondmanca/djangorestframework-api-key#197]
Hey! Im currently using this amazing library to store API Keys for users, each API Key is used for some services in my API.

Each User is connected to a APIKey.

```
class UserApiKey(AbstractAPIKey):
    """
    APIKey model
    """

    user = models.ForeignKey(User, on_delete=models.DO_NOTHING,
                             related_name='api_keys',
                             verbose_name='User')
```

As a user, I want to retrieve all available API Keys, is there any way to fetch them all? My problem is that API Keys are hashed, and I want to list all client available API Keys.

**Comment by florimondmanca** [comment]
Hi @MatthiasMuller,

This library was actually _designed_ to prevent the server from reading API keys in cleartext once they've been generated.

If your use case is something like "list available API keys", and does not imply having access to the actual API key (the value that clients send with requests), would the API key _prefixes_ be sufficient?

```python
api_keys = UserApiKey.objects.all()
prefixes = [api_key.prefix for api_key in api_keys]  # ['PdIgApov', ...]
```
