### ISSUE TITLE
Ensured Django 4 support

### ISSUE THREAD

**Issue by florimondmanca** [florimondmanca/djangorestframework-api-key#205]
Currently, we're testing against Django 3.2 max.

But Django 4.0 was released in December 2021: https://www.djangoproject.com/weblog/2021/dec/07/django-40-released/ and 4.1 is just around the corner (alpha state).

Let's ensure this library has continued support for this newer Django major series.

**Comment by KyleBehielsCertn** [comment]
@florimondmanca Was wondering if there was any progress on this or plans to support Django 4.x now that it's in LTS. TIA

**Comment by florimondmanca** [comment]
Hi @KyleBehielsCertn 

This ticket is up for grabs for anyone who’s like to help advance it

Lemme jot down what I think needs to be done to close this off…

- Add a step to CI to test under the latest Django 4 version (or should we choose latest Django 4 LTS?)
- Take note of any broken tests and fix those
- Add a trove classifier for Django 4, so it shows in the README badge

That should do the trick. Then we can package this change into a new version.

**Comment by florimondmanca** [comment]
@KyleBehielsCertn Thanks to @fgrassals we merged #235 which revealed no changes were required for 4.2.x support. There should be a release soon, but this means the package should work out of the box even in the current version. Unless you'd report otherwise! Thanks.
