### ISSUE TITLE
`KeyParser` should match `keyword` exactly

### ISSUE THREAD

**Issue by Kostia-K** [florimondmanca/djangorestframework-api-key#218]
`KeyParser` matches if authentication scheme ends with the keyword. I suppose, this situation shouldn't come up in most use cases but this behaviour is surprising nonetheless. Example:

```python
from rest_framework_api_key.permissions import KeyParser

class Request:
    pass

request = Request()
request.META = {"HTTP_AUTHORIZATION": "My-Special-Api-Key 123456789"}

# prints the key 123456789
print(KeyParser().get(request))
```

In comparison, Django Rest Framework `TokenAuthentication` matches the keyword exactly (case-insensitive): https://github.com/encode/django-rest-framework/blob/master/rest_framework/authentication.py#L177

**Comment by florimondmanca** [comment]
That sounds inappropriate, yup. Marked this as a bug. Anyone up for digging into this, much welcome!
