### ISSUE TITLE
HasApiKeyAndIsAuthenticated permission. 

### ISSUE THREAD

**Issue by orlax** [florimondmanca/djangorestframework-api-key#23]
**Is your feature request related to a problem? Please describe.**
Hey, i am using this library for a python backend with a react-native mobile client and them some API rest users. So one of my permissions setups requires the user to both use an Api key to authenticate the client (be that an app or third-party server using the API) and them some JWT to authenticate the specific user making the request, for example: 

listing an history of items from the DB should only be possible when the requests comes from the mobile app and the user is logged. So that an user cant not access the API from outside the application unless i give them an APIKey

**Describe the solution you'd like**
Implement an HasApiKeyAndIsAuthenticated class on permissions.py, as i did here: 

    `
    class HasAPIKeyAndIsAuthenticated(permissions.BasePermission):
     """Authorize if a valid API key is provided and the request is authenticated."""
        def has_permission(self, request, view):
            if(HasAPIKey().has_permission(request, view) and 
    permissions.IsAuthenticated().has_permission(request, view)): 
                return True
            else: 
                return False
`

**Describe alternatives you've considered**
Is there a reason why this is not implemented already? would it be considered a bad practice?

**Comment by florimondmanca** [comment]
Hi @orlax, thanks for reporting this!

> Is there a reason why this is not implemented already? would it be considered a bad practice?

No particular reason this isn't implemented yet — we have `HasAPIKeyOrIsAuthenticated` already, so I'm fine with adding the `And` version. Besides, your use case makes total sense. :+1:

To be honest, my bandwith for working on this package is quite limited at the moment. Since you already seem to have a working implementation, would you be willing to give this a shot? If so, you can find some help on contributing in the [contributing guidelines](https://github.com/florimondmanca/djangorestframework-api-key/blob/master/CONTRIBUTING.md).

**Comment by orlax** [comment]
[Hope this is Ok?](https://github.com/florimondmanca/djangorestframework-api-key/pull/24) first time making a pull request here on github. Let me know. 

i just saw there is another pull request #19 that uses a single header authorization, with the keyword "Authorization". As far as i can tell this would create a conflict with the [default token base authentication on Django REST](tokenauthenticationtokenauthentication) wich would require users using that along this library to have to change the keyword ¿? just something i realized.

**Comment by florimondmanca** [comment]
Thanks for the PR! I’ll review it when I have some time, but looks good already!

> this would create a conflict with the default token base authentication on Django REST

Wow, you’re right — we wouldn’t be able to use API key and token based auth together. We definitely need to fix this :-) I think using a custom header like X-Api-Key would fix it.

**Comment by florimondmanca** [comment]
@orlax As we discussed, this should now be easy to implement in 1.0. I’m closing this but feel free to reopen if you encounter any issues. :-)
