### ISSUE TITLE
API_KEY_CUSTOM_HEADER not working

### ISSUE THREAD

**Issue by seed-doordash** [florimondmanca/djangorestframework-api-key#230]
**Describe the bug**
API_KEY_CUSTOM_HEADER not working  as expected following the guide.
- putting `API_KEY_CUSTOM_HEADER = "HTTP_X_API_KEY" into settings.py. 
- testing by running
❯ curl -X 'GET' \
  'http://localhost:8000/test/' \
  -H 'accept: application/json' \
  -H 'X_API_KEY: xxxxxxxxxx.xxxxxxxxx'

This does not seem to put the headers into request.Meta and I cannot grab the key via request.META["HTTP_X_API_KEY"]

**Desktop (please complete the following information):**
 - OS: macOs
 - Python Version: 3.10.1
 - Django Version: 4.1.5
 - DRF Version: 3.14.0

**Additional context**

**Comment by seed-doordash** [comment]
Ah. It seems DRF/django filter out any header with underscore?
It works if i change the custom header to things like `apikey`

Should we update the README?

**Comment by florimondmanca** [comment]
Hi @seed-doordash,

Seeing this just now as I visit the repo again.

Initially you should have been sending a header named `X-Api-Key`, not `X_API_KEY`. As far as I understand, Django's META contains headers named in all uppercase with `-` changed to `_`.

Greetings!
