### ISSUE TITLE
API Key object pk/id created with api-key and hashed api key

### ISSUE THREAD

**Issue by umair313** [florimondmanca/djangorestframework-api-key#245]
Hey, what is the reason for saving API-key.Hached API-key in as id?
is there some thing specific to security or what?
Thanks

**Comment by florimondmanca** [comment]
Hi @umair313 

You can get more context around this issue in #128 and related discussions.

This can be considered a historical design "flaw". I can't exactly remember the reason why I went with this design. My feeling is that we could move to traditional integer PKs without regret. Please feel free to comment and discuss on #128 if you have more ideas on this topic.

Thanks!
