### ISSUE TITLE
There is no clearly documented way to manually validate an API key

### ISSUE THREAD

**Issue by jabelone** [florimondmanca/djangorestframework-api-key#256]
I have a web socket endpoint that various IoT devices talk to. The first web socket message must contain a valid API key otherwise the web socket connection is terminated. To support this use case, I need to manually verify if an API key is valid from within a Django Channels WebsocketConsumer.

After digging through a bunch of previous issues, PRs, and the codebase, it appears that I can use a manager method to check if a given string is a valid API key. My understanding is that this should return `True` if the `raw_key` exists, is not revoked, and is not expired; or `False` otherwise: 

```python
class MyCustomAPIKey(AbstractAPIKey):
    pass

is_valid_key = MyCustomAPIKey.objects.is_valid(raw_key)
```

Is this the correct use of that method? If so, I'll add some documentation and an example to make it more clear.

I also noticed the instance method `is_valid()` on `AbstractAPIKey` has a different implementation to `is_valid()` on `BaseAPIKeyManager` and doesn't appear to check the expiry date. Is this difference intentional?

**Comment by florimondmanca** [comment]
Hi @jabelone,

That’s right, you should use the manager’s is_valid() method, essentially reproducing the code from the permission class. Actually, would it make sense for you to reuse the permission class? I don’t know about Django channels + permissions but if there’s a permission mechanism provided by Django channels, you might as well use it.

The is_valid() method on model instances only checks for hash-to-hash validity, and it gets called by the manager method (I’d agree they could have been called different names).

**Comment by jabelone** [comment]
> That’s right, you should use the manager’s is_valid() method

Great, thanks for confirming! It doesn't look like there's anything supported by channels straight out of the box, so I'll just validate it in the Channels `JsonWebsocketConsumer` `connect()` handler for now.

> The is_valid() method on model instances only checks for hash-to-hash validity

Ah that makes sense, I've included a note about that in the documentation PR so people don't get confused.
