### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by florimondmanca** [florimondmanca/djangorestframework-api-key#64]
**Is your feature request related to a problem? Please describe.**
This package currently hardcodes strings such as verbose names and help texts, which means we can't generate translations for it.

**Describe the solution you'd like**

```python
from django.utils.translation import gettext_lazy as _
```

and use `_("...")` everywhere. :+1:

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by florimondmanca** [comment]
Closing to help reduce scope, but happy to reconsider if anyone's up for it!

**Comment by davidmarogy** [comment]
It would be realy great, if internalization could be implemented in a next release :).

**Comment by parasiteoflife** [comment]
could this be reopened and close as not planned? As it is right now it looks like it is implemented and it wasn't until I actually opened the issue that I saw it was closed without implementation.


Or just reopened? #269
