### ISSUE TITLE
1.4 release date

### ISSUE THREAD

**Issue by deshraj** [florimondmanca/djangorestframework-api-key#67]
@florimondmanca: Can you please let us know what is the plan for V1.4 release? The feature of storing `prefix` and `hashed_key` separately in the AbstractAPIKey model is something that we are looking forward to.

Thanks again for this really nice package. :) (Please feel free to close this issue)

**Comment by florimondmanca** [comment]
Hi! Thanks for your interest, I think we can safely bet on a release happening this weekend. 👍

**Comment by deshraj** [comment]
Thanks @florimondmanca for the quick reply.

**Comment by florimondmanca** [comment]
@deshraj 1.4 just released. :+1:
