### ISSUE TITLE
The document doesn't fully cover the custom model scenario.

### ISSUE THREAD

**Issue by cansarigol** [florimondmanca/djangorestframework-api-key#76]
Hi, Today I used your project into my project. I tried to apply the custom model. After migration, my custom model has been created on DB. I created a new row from admin and I got the key. However, this key didn't work. Because validation still looked `APIKey` due to `permission_classes = HasApiKey` configuration.

So I added my own `HasAPIKey` class with my custom model and the problem was solved. I thought that this situation can be added to the document. 

```
from rest_framework_api_key.permissions import BaseHasAPIKey
class ClientHasAPIKey(BaseHasAPIKey):
    model = ClientAPIKey

permission_classes = ClientHasAPIKey
```

**Comment by florimondmanca** [comment]
Hi @cansarigol! Nice to see you here. Did you see the [Permission classes](https://florimondmanca.github.io/djangorestframework-api-key/guide/#permission-classes) section of the documentation? It seems to document this use case already. Is there anything missing?

**Comment by cansarigol** [comment]
Btw project and document awesome :+1: :rocket: thanks for this development

**Comment by cansarigol** [comment]
Ahh so sorry after I finished to read the admin panel, I didn't continue the next section. Completely my mistake sorry. unnecessarily I made inferences from the code.

**Comment by florimondmanca** [comment]
Coolio, and thanks for the kind words! I think once #61 gets through this project will be in even better shape — but unfortunately we haven't be able to find time to finish that up yet.
